name: riverpod_management
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  dio_http_formatter: ^3.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
